#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.50
yabai -m config window_border                off
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8

# Specific rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add title="Preferences$" manage=off
yabai -m rule --add title="^About$" manage=off
yabai -m rule --add title="Info$" manage=off
yabai -m rule --add title="^Battle.net Login$" manage=off
yabai -m rule --add title="^Discord Updater$" manage=off
yabai -m rule --add title="About This Mac" manage=off
yabai -m rule --add title="^1Password" manage=off
yabai -m rule --add title="^Leapp" manage=off
yabai -m rule --add app="Messages" manage=off
yabai -m rule --add app="Notes" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="1Password" manage=off
yabai -m rule --add app="Leapp" manage=off
yabai -m rule --add app="Screen Studio" manage=off

echo "yabai configuration loaded.."
