#!/usr/bin/env sh

spacebar -m config position             top
spacebar -m config height               24
spacebar -m config title                on
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config padding_left         18
spacebar -m config padding_right        12
spacebar -m config spacing_left         24
spacebar -m config spacing_right        18
spacebar -m config text_font            "JetBrains Mono:Bold:12.0"
spacebar -m config icon_font            "Font Awesome 5 Free:Solid:12.0"
spacebar -m config background_color     0xff2e3340
spacebar -m config foreground_color     0xffd8dee8
spacebar -m config space_icon_color     0xffbf6069
spacebar -m config power_icon_color     0xffeacb8a
spacebar -m config battery_icon_color   0xffeacb8a
spacebar -m config dnd_icon_color       0xff81a1c1
spacebar -m config clock_icon_color     0xff81a1c1
spacebar -m config right_shell_icon_color 0xff81a1c1
spacebar -m config power_icon_strip      
spacebar -m config space_icon_strip     • • • • • • •
spacebar -m config space_icon           
spacebar -m config clock_icon           
spacebar -m config dnd_icon             
spacebar -m config clock_format         "%Y-%m-%d %R"
spacebar -m config right_shell          on
spacebar -m config right_shell_icon     
spacebar -m config right_shell_command  "whoami"

echo "spacebar configuration loaded.."
