#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -r ~/sxhkd.log &
compton &
xrandr --output DP-0 --mode 2560x1440 --rate 144
pacmd set-default-sink "alsa_output.usb-FiiO_DigiHug_USB_Audio-01.iec958-stereo"
pacmd set-default-source "alsa_input.usb-Blue_Microphones_Yeti_Stereo_Microphone_797_2020_01_06_11901-00.analog-stereo"
feh --bg-scale $HOME/Pictures/background.jpg &
eval $(gnome-keyring-daemon -s -- components=pkcs11,secrets,ssh,gpg) & 
bash $HOME/.config/polybar/launch.sh &
unclutter &
greenclip daemon &

bspc monitor -d I II III IV V VI

bspc config border_width 2
bspc config window_gap8
bspc config focused_border_color "#65737e"
bspc config normal_border_color "#2b303b"

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config top_padding 26
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc rule -a "quick-note-window" state=floating layer=above
